import { seo } from '../seo.mjs';
import { layout, icon, disclosureBand, ctaBand, lastReviewed } from '../components.mjs';
import { serviceFacts, programs, organization, externalFlows, tradingConduct } from '../site-facts.mjs';

const meta = seo({
  title: 'Crypto Prop Trading | Simulated Accounts Up to $200K | Your Funded Account',
  description: 'Compare 1-Step, 2-Step and instant-funded crypto trading programs. Trade virtual funds under clear risk rules and qualify for performance-based USDT payouts under the applicable terms.',
  path: '/',
});

const chartSvg = `<svg class="hero-chart" viewBox="0 0 640 250" role="img" aria-label="Illustrative crypto market chart">
  <defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#00b5ab" stop-opacity=".28"/><stop offset="1" stop-color="#00b5ab" stop-opacity="0"/></linearGradient></defs>
  <g class="grid"><path d="M0 50H640M0 100H640M0 150H640M0 200H640"/><path d="M100 0V250M200 0V250M300 0V250M400 0V250M500 0V250M600 0V250"/></g>
  <path class="area" d="M0 210 L32 198 L64 204 L96 168 L128 176 L160 150 L192 160 L224 118 L256 134 L288 112 L320 124 L352 85 L384 96 L416 68 L448 80 L480 55 L512 62 L544 40 L576 50 L608 32 L640 38 L640 250 L0 250Z"/>
  <path class="line" d="M0 210 L32 198 L64 204 L96 168 L128 176 L160 150 L192 160 L224 118 L256 134 L288 112 L320 124 L352 85 L384 96 L416 68 L448 80 L480 55 L512 62 L544 40 L576 50 L608 32 L640 38"/>
</svg>`;

const body = `
<section class="hero-home"><div class="wrap hero-home-grid">
  <div class="hero-copy"><div class="eyebrow">Crypto-focused simulated trading evaluations</div><h1>Trade crypto<br>with up to <span>$200K</span></h1><p class="lead">Choose a 1-Step or 2-Step evaluation, or explore an eligible instant-funded program. Trade virtual funds under defined risk limits and qualify for performance-based USDT payouts under the applicable terms.</p>
    <div class="hero-actions"><a class="btn btn-primary btn-lg" href="#programs">Compare programs</a><a class="btn btn-ghost btn-lg" href="/rules/">Read the trading rules</a></div>
    <div class="hero-facts"><div><strong>350+</strong><span>USDT perpetual markets</span></div><div><strong>Up to $200K</strong><span>account size</span></div><div><strong>No expiry</strong><span>evaluation clock</span></div></div>
  </div>
  <div class="market-stage" aria-label="Illustrative market environment preview"><div class="stage-label"><span>Illustrative market view</span><b>BTC/USDT · Perpetual</b><em>Simulated</em></div>${chartSvg}<div class="stage-bottom"><div><span>Environment</span><b>Virtual funds</b></div><div><span>Settlement asset</span><b>USDT</b></div><div><span>Risk rules</span><b>Published</b></div></div></div>
</div></section>
${disclosureBand()}
<section class="service-definition"><div class="wrap service-definition-grid"><div><span class="section-index">01</span><h2>Crypto prop trading with the model stated upfront.</h2></div><p><strong>${organization.brandName}</strong> is a crypto-focused simulated trading evaluation platform built around virtual-fund programs, published risk limits and performance-based payouts. Customer trading accounts do not hold deposits or deploy customer capital.</p></div></section>
<section id="programs" class="section program-section"><div class="wrap"><div class="section-heading split"><div><div class="eyebrow">Choose your path</div><h2>Compare every route to funding in one place.</h2></div><p>Switch between 1-Step, 2-Step and Instant Funding. The comparison focuses on the rules and account details that matter before you choose a program.</p></div>
  <div class="program-config" data-config>
    <div class="program-tabs" role="tablist" aria-label="Programs"><button class="program-tab active" data-program="one" role="tab" aria-selected="true">1-Step</button><button class="program-tab" data-program="two" role="tab" aria-selected="false">2-Step</button><button class="program-tab" data-program="instant" role="tab" aria-selected="false" aria-label="Instant Funding">Instant</button></div>
    <div class="program-panel"><div class="program-intro"><span class="config-kicker">Selected program</span><h3 id="programTitle">${programs.one.label}</h3><p id="programSummary">Pass one evaluation phase under the current target and drawdown rules.</p><div id="sizeSelector" class="size-selector hidden" aria-live="polite"></div></div><dl id="programRules" class="rule-list"><div><dt>Profit target</dt><dd>10%</dd></div><div><dt>Daily drawdown</dt><dd>3%</dd></div><div><dt>Total drawdown</dt><dd>6%</dd></div><div><dt>Profitable days</dt><dd>3</dd></div><div><dt>Time limit</dt><dd>No expiry</dd></div></dl><div class="program-action"><span class="config-kicker">Current fee</span><strong id="programPrice">Live at checkout</strong><p id="programPriceNote">Evaluation pricing is intentionally not duplicated until connected to the live pricing source.</p><a id="programCta" class="btn btn-primary" href="${externalFlows.checkout}">View live options</a></div></div>
  </div>
  <p class="source-line">Program structure last reviewed 2026-08-21. Exact checkout pricing remains owned by the live transaction source.</p>
</div></section>
<section class="section product-section"><div class="wrap product-grid"><div><div class="eyebrow">Crypto trading, not a forex add-on</div><h2>350+ USDT perpetual markets. One simulated trading environment.</h2><p>Market coverage is one of the clearest points of differentiation. The public product is positioned around crypto-native perpetual markets and USDT settlement.</p><div class="instrument-row"><span>BTC/USDT</span><span>ETH/USDT</span><span>SOL/USDT</span><span>XRP/USDT</span><span>+ 346 more</span></div><a class="text-link" href="/instruments/">Explore market coverage ${icon('arrow')}</a></div>
  <div class="market-board"><div class="board-top"><b>Market environment</b><span>Illustrative presentation · not a product screenshot</span></div>${chartSvg}<div class="quote-grid"><div><span>Model</span><strong>Simulated</strong></div><div><span>Settlement</span><strong>USDT</strong></div><div><span>Evaluation expiry</span><strong>None</strong></div><div><span>Maximum account size</span><strong>$200K</strong></div></div></div>
</div></section>
<section class="conduct-section"><div class="wrap"><div class="section-heading"><div class="eyebrow">Rules become product evidence</div><h2>Know what is allowed before you pay.</h2><p>Instead of generic “flexibility” claims, YFA surfaces actual conduct rules.</p></div><div class="conduct-grid"><article class="conduct allowed"><div class="conduct-title">${icon('check')}<div><span>Currently allowed</span><h3>Trade inside the risk framework.</h3></div></div>${tradingConduct.allowed.map(([a,b])=>`<div class="conduct-row"><strong>${a}</strong><p>${b}</p></div>`).join('')}</article><article class="conduct prohibited"><div class="conduct-title">${icon('close')}<div><span>Currently prohibited</span><h3>No hidden “gotcha” category.</h3></div></div>${tradingConduct.prohibited.slice(0,4).map(([a,b])=>`<div class="conduct-row"><strong>${a}</strong><p>${b}</p></div>`).join('')}</article></div><div class="conduct-link"><a class="btn btn-ghost" href="/rules/">Read the canonical rule summary</a></div></div></section>
<section class="section how-section"><div class="wrap"><div class="section-heading"><div class="eyebrow">How it works</div><h2>A four-step qualification path.</h2></div><ol class="steps"><li><span>01</span><h3>Choose a program</h3><p>Compare the evaluation structures and current risk limits.</p></li><li><span>02</span><h3>Trade virtual funds</h3><p>Use the simulated environment and stay inside the published rules.</p></li><li><span>03</span><h3>Meet the target</h3><p>Complete the applicable profit target and profitable-day requirements.</p></li><li><span>04</span><h3>Progress and request</h3><p>Eligible funded-stage traders may submit payout requests under the applicable terms.</p></li></ol></div></section>
<section class="payout-band"><div class="wrap payout-band-grid"><div><div class="eyebrow light">Payout process</div><h2>Performance rewards are reviewed, not promised.</h2></div><div><p>Eligible funded-stage traders may submit a payout request after meeting the applicable account requirements. Requests are reviewed under the current Terms and Conditions and paid in USDT when approved.</p><div class="inline-links"><a href="/withdrawals/">Payout transparency</a><a href="/rules/#payouts">Payout rules</a><a href="/terms-and-conditions/">Terms</a></div></div></div></section>
<section class="section trust-section"><div class="wrap"><div class="section-heading split"><div><div class="eyebrow">Operator & model</div><h2>Know who operates the platform and how the model works.</h2></div>${lastReviewed('Product, Risk & Legal')}</div><div class="trust-ledger"><div><span>Legal operator</span><strong>${organization.legalName}</strong><p>Reg. No. ${organization.registrationNumber}</p></div><div><span>Jurisdiction</span><strong>${organization.registeredZone}</strong><p>${organization.jurisdiction}</p></div><div><span>Trading model</span><strong>Simulated environment</strong><p>Virtual funds; no customer deposits.</p></div><div><span>Payout asset</span><strong>USDT</strong><p>Subject to eligibility and approval.</p></div></div><div class="trust-actions"><a href="/about/">Company & model</a><a href="/risk-disclosure/">Risk disclosure</a><a href="/terms-and-conditions/">Terms</a><a href="/privacy-policy/">Privacy</a></div></div></section>
<section class="section faq-preview"><div class="wrap"><div class="section-heading split"><div><div class="eyebrow">Questions before checkout</div><h2>Straight answers before you commit.</h2></div><a class="text-link" href="/faq/">View full FAQ ${icon('arrow')}</a></div><div class="faq-list compact" data-faq><article><button aria-expanded="false">Are YFA accounts live-capital accounts?<span>+</span></button><div><p>No. Evaluation and funded-stage trading uses simulated virtual funds.</p></div></article><article><button aria-expanded="false">Does the 1-Step evaluation expire?<span>+</span></button><div><p>No evaluation expiry is currently listed for the 1-Step program.</p></div></article><article><button aria-expanded="false">Can positions stay open over the weekend?<span>+</span></button><div><p>Yes. Overnight and weekend holding is currently allowed under the published rules.</p></div></article><article><button aria-expanded="false">How are approved payouts settled?<span>+</span></button><div><p>The current public model uses USDT for approved performance-based payouts.</p></div></article></div></div></section>
${ctaBand('Your strategy. Your funded account.', 'Compare the program rules first, then continue to the current transaction flow.')}`;

export default { path:'/', seo:meta, html: layout({ seo:meta, path:'/', body }) };
